PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS "MEASUREMENT";
CREATE TABLE IF NOT EXISTS "MEASUREMENT" (
	"completionTime"	NUMERIC NOT NULL,
	"sensorID"	INTEGER NOT NULL,
	"roomID"	INTEGER NOT NULL,
	"batteryLeft"	NUMERIC NOT NULL,
	"temperature"	INTEGER NOT NULL,
	"humidity"	NUMERIC NOT NULL,
	PRIMARY KEY("completionTime","sensorID","roomID"),
	FOREIGN KEY("sensorID","roomID") REFERENCES "SENSOR"("sensorID","roomID") ON UPDATE CASCADE ON DELETE CASCADE
);
DROP TABLE IF EXISTS "SENSOR";
CREATE TABLE IF NOT EXISTS "SENSOR" (
	"sensorID"	INTEGER NOT NULL,
	"roomID"	INTEGER NOT NULL,
	"manufacturer"	TEXT NOT NULL,
	"temperatureAccuracy"	NUMERIC NOT NULL,
	"humidityAccuracy"	NUMERIC NOT NULL,
	"maxBatteryLife"	INTEGER NOT NULL,
	PRIMARY KEY("sensorID","roomID"),
	FOREIGN KEY("roomID") REFERENCES "ROOM"("roomID") ON UPDATE CASCADE ON DELETE CASCADE
);
DROP TABLE IF EXISTS "ROOM";
CREATE TABLE IF NOT EXISTS "ROOM" (
	"roomID"	INTEGER NOT NULL,
	"floor"	INTEGER NOT NULL,
	"area"	INTEGER NOT NULL,
	PRIMARY KEY("roomID")
);
INSERT INTO "ROOM" VALUES (1,1,43);
INSERT INTO "ROOM" VALUES (2,1,56);
INSERT INTO "ROOM" VALUES (3,2,70);
INSERT INTO "ROOM" VALUES (4,3,43);
INSERT INTO "ROOM" VALUES (5,4,56);
INSERT INTO "SENSOR" VALUES (1,1,'lg','95%','92%',1000);
INSERT INTO "SENSOR" VALUES (1,2,'lg','94%','93%',800);
INSERT INTO "SENSOR" VALUES (2,3,'lg','99%','95%',400);
INSERT INTO "SENSOR" VALUES (3,4,'lg','98%','91%',2000);
INSERT INTO "SENSOR" VALUES (4,5,'lg','96%','90%',1500);
INSERT INTO "MEASUREMENT" VALUES ('20:30',1,1,'87%',23,'67%');
INSERT INTO "MEASUREMENT" VALUES ('17:36',1,2,'95%',17,'72%');
INSERT INTO "MEASUREMENT" VALUES ('4:12',2,3,'57%',19,'56%');
INSERT INTO "MEASUREMENT" VALUES ('10:49',3,4,'25%',26,'77%');
INSERT INTO "MEASUREMENT" VALUES ('23:52',4,5,'42%',15,'70%');
INSERT INTO "ROOM" VALUES (1,2,56);
INSERT INTO "SENSOR" VALUES (1,1,'xiaomi','77%','54%',950);
INSERT INTO "MEASUREMENT" VALUES ('20:30',1,1,'54%',26,'87%');
SELECT * FROM "ROOM";
SELECT * FROM "SENSOR";
SELECT * FROM "MEASUREMENT";
DELETE FROM "SENSOR" WHERE "roomID" = 1;
SELECT * FROM "ROOM";
SELECT * FROM "SENSOR";
SELECT * FROM "MEASUREMENT";
DELETE FROM "MEASUREMENT" WHERE "roomID" = 1;
DELETE FROM "MEASUREMENT" WHERE "sensorID" = 1;
SELECT * FROM "ROOM";
SELECT * FROM "SENSOR";
SELECT * FROM "MEASUREMENT";
UPDATE "SENSOR"
SET "roomID" = "roomID" + 1
WHERE "roomID" = 2;
SELECT * FROM "ROOM";
SELECT * FROM "SENSOR";
SELECT * FROM "MEASUREMENT";
UPDATE "MEASUREMENT"
SET "roomID" = "roomID" + 1
WHERE "roomID" = 2;
UPDATE "MEASUREMENT"
SET "sensorID" = 1
WHERE "sensorID" = 2;
SELECT * FROM "ROOM";
SELECT * FROM "SENSOR";
SELECT * FROM "MEASUREMENT";
COMMIT;
